### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by ramonck** [facundoolano/aso#2]
On the README section you putted "npm install aso", I think you meant "npm install ." tried doing the aso and it seems it's not in npm.

![image](https://cloud.githubusercontent.com/assets/5229948/15858637/e49875ac-2c97-11e6-93d7-1d3103924739.png)

**Comment by facundoolano** [comment]
The `npm install aso` in the README is meant to install the project into any folder (usually as a dependency of another node.js project). If you cloned the git repo you don't need to install the aso module in that directory (since you already have the code), just npm install to get its dependencies.

If you try `npm install aso` in any other directory (that doesn't have the module code in it), you'll see it works.

Closing this, reopen if you still have issues.

**Comment by ramonck** [comment]
"npm install aso" doesn't work on Windows, but the project downloaded works in Windows.

**Comment by facundoolano** [comment]
Unfortunately I don't have a win computer around to test this. The project setup is pretty standard, tough, maybe there's an issue with your npm installation?

Anyway, using the cloned version is the same, just bare in mind that the repo may contain unfinished/untested changes, so better stick to [relase commits](https://github.com/facundoolano/aso/releases).
